- alias: juani
  email: juanigalarza98@gmail.com
  gpgkey: juanigalarza98-gmail-com.asc
- alias: Ash
  email: ashgalarza@gmail.com
  gpgkey: ashgalarza-gmail-com.asc
- alias: Sofi
  email: sofimilessi19@gmail.com
  gpgkey: sofimilessi19-gmail-com.asc
